version: '3'

services:
  redis-node1:
    image: redis
    command: ["redis-server", "--port", "7000", "--cluster-enabled", "yes"]
    ports:
      - "7000:7000"
    networks:
      - redis-cluster

  redis-node2:
    image: redis
    command: ["redis-server", "--port", "7001", "--cluster-enabled", "yes"]
    ports:
      - "7001:7001"
    networks:
      - redis-cluster

  redis-node3:
    image: redis
    command: ["redis-server", "--port", "7002", "--cluster-enabled", "yes"]
    ports:
      - "7002:7002"
    networks:
      - redis-cluster

  redis-node4:
    image: redis
    command: ["redis-server", "--port", "7003", "--cluster-enabled", "yes"]
    ports:
      - "7003:7003"
    networks:
      - redis-cluster

  redis-node5:
    image: redis
    command: ["redis-server", "--port", "7004", "--cluster-enabled", "yes"]
    ports:
      - "7004:7004"
    networks:
      - redis-cluster

  redis-node6:
    image: redis
    command: ["redis-server", "--port", "7005", "--cluster-enabled", "yes"]
    ports:
      - "7005:7005"
    networks:
      - redis-cluster

networks:
  redis-cluster:
    driver: bridge
